name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    
    - name: Run tests with pytest
      run: |
        uv sync
        uv run python -m pytest tests
    
    - name: Upload coverage as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage.xml
